### PR TITLE
Ignore all whitespace delimiters in email address lists

### LINKED ISSUE #33: Misleading error message when Cc field contains malformed address
#### Reproduction steps

1. Start TripleA client.
1. Start a new PBEM/PBF game.
1. Enter a registered email in the Dice Server **To** field.
1. Enter a registered email in the Dice Server **Cc** field and add a trailing space.
1. Enter a value in the **Game ID** field.
1. Click **Test Server**.

#### Expected behavior

MARTI should indicate the address in the **Cc** field is not registered.

#### Actual behavior

MARTI indicates the address in the **To** field is not registered.

#### Notes

Originally from an axisandallies.org thread ending [here](https://www.axisandallies.org/forums/index.php?topic=41182.msg1729160#msg1729160).

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #33.

These fields are space-delimited lists of email addresses.  The `explode()` function only ignores a single space delimiter between each address.  If there are any leading or trailing spaces, or more than one space between each address, the resulting list will contain an empty address.  As an empty address will never be registered, MARTI will refuse to process the dice roll request.

The fix is to split the string regardless of the number of whitespace delimiters before, between, and after each address.

#### Testing

I tested the following scenarios:

* Multiple space characters before To address.
* Multiple space characters after To address.
* Multiple space characters between two To addresses.
* Multiple space characters before Cc address.
* Multiple space characters after Cc address.
* Multiple space characters between two Cc addresses.

### CODE REVIEW

File: src/MARTI.php [hunk 1]
```diff
@@ -26,8 +26,8 @@
 			exit("fatal error: no second email found. Please enter an email address into the CC-field!");
 		}
 		//format multiple emails in one line
-		$emails1 = explode(" ", $email1);
-		$emails2 = explode(" ", $email2);
+		$emails1 = preg_split("/\s+/", $email1, -1, PREG_SPLIT_NO_EMPTY);
+		$emails2 = preg_split("/\s+/", $email2, -1, PREG_SPLIT_NO_EMPTY);
```
Comment (RoiEXLab) [inline src/MARTI.php:30]: What about using
```php
$emails = explode(" ", trim($email))
```
?

Comment (ssoloff) [reply src/MARTI.php:30]: Tried that first, but it doesn't handle the case when there are multiple spaces _between_ addresses.

**Review by RoiEXLab — APPROVED** [review]
